---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: camel-kcp
rules:
- apiGroups:
  - apis.kcp.dev
  resources:
  - apiexports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apis.kcp.dev
  resources:
  - apiexports/content
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
