apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
kind: ControllerManagerConfig
service:
  apiExportName: camel-kcp
  onApiBinding:
    createDefaultPlatform:
      metadata:
        namespace: camel-k
        name: camel-k
      spec:
        build:
          registry:
            address: REGISTRY_ADDRESS # kpt-set: ${registry-address}
            insecure: true
    createDefaultPlacement:
      metadata:
        name: default
      spec:
        locationWorkspace: root:camel-k
        locationResource:
          group: workload.kcp.dev
          resource: synctargets
          version: v1alpha1
        namespaceSelector: {}
        locationSelectors:
        - matchExpressions:
          - key: org.apache.camel/data-plane
            operator: Exists
