apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
kind: ControllerManagerConfig
service:
  apiExports:
    camel-k:
      apiExportName: camel-k
      onApiBinding:
        createDefaultPlatform:
          metadata:
            namespace: camel-k
            name: camel-k
          spec:
            build:
              registry:
                address: REGISTRY_ADDRESS # kpt-set: ${registry-address}
                insecure: true
              baseImage: eclipse-temurin:11 # TODO: Remove once upgrade to latest Camel K
        createDefaultPlacement:
          metadata:
            name: default
          spec:
            locationWorkspace: root:camel-kcp # kpt-set: ${camel-kcp-workspace}
            locationResource:
              group: workload.kcp.io
              resource: synctargets
              version: v1alpha1
            namespaceSelector:
              matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: NotIn
                values:
                - kaoto
            locationSelectors:
            - matchExpressions:
              - key: org.apache.camel/data-plane
                operator: Exists
    kaoto:
      apiExportName: kaoto
      onApiBinding:
        createDefaultPlacement:
          metadata:
            name: kaoto
          spec:
            locationWorkspace: root:camel-kcp # kpt-set: ${camel-kcp-workspace}
            locationResource:
              group: workload.kcp.io
              resource: synctargets
              version: v1alpha1
            namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: kaoto
            locationSelectors:
            - matchExpressions:
              - key: org.apache.camel/data-plane
                operator: Exists
