apiVersion: apps/v1
kind: Deployment
metadata:
  name: camel-kcp
spec:
  template:
    spec:
      containers:
      - name: manager
        image: REGISTRY_ADDRESS/camel-kcp # kpt-set: ${registry-address}/camel-kcp
        imagePullPolicy: Always
