//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package config

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIExports) DeepCopyInto(out *APIExports) {
	*out = *in
	in.CamelK.DeepCopyInto(&out.CamelK)
	in.Kaoto.DeepCopyInto(&out.Kaoto)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIExports.
func (in *APIExports) DeepCopy() *APIExports {
	if in == nil {
		return nil
	}
	out := new(APIExports)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CamelKAPIExport) DeepCopyInto(out *CamelKAPIExport) {
	*out = *in
	out.LocalAPIExportReference = in.LocalAPIExportReference
	in.OnAPIBinding.DeepCopyInto(&out.OnAPIBinding)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CamelKAPIExport.
func (in *CamelKAPIExport) DeepCopy() *CamelKAPIExport {
	if in == nil {
		return nil
	}
	out := new(CamelKAPIExport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationPlatform) DeepCopyInto(out *IntegrationPlatform) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationPlatform.
func (in *IntegrationPlatform) DeepCopy() *IntegrationPlatform {
	if in == nil {
		return nil
	}
	out := new(IntegrationPlatform)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KaotoAPIExport) DeepCopyInto(out *KaotoAPIExport) {
	*out = *in
	out.LocalAPIExportReference = in.LocalAPIExportReference
	in.OnAPIBinding.DeepCopyInto(&out.OnAPIBinding)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KaotoAPIExport.
func (in *KaotoAPIExport) DeepCopy() *KaotoAPIExport {
	if in == nil {
		return nil
	}
	out := new(KaotoAPIExport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalAPIExportReference) DeepCopyInto(out *LocalAPIExportReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalAPIExportReference.
func (in *LocalAPIExportReference) DeepCopy() *LocalAPIExportReference {
	if in == nil {
		return nil
	}
	out := new(LocalAPIExportReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OnCamelKAPIBinding) DeepCopyInto(out *OnCamelKAPIBinding) {
	*out = *in
	if in.DefaultPlatform != nil {
		in, out := &in.DefaultPlatform, &out.DefaultPlatform
		*out = new(IntegrationPlatform)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultPlacement != nil {
		in, out := &in.DefaultPlacement, &out.DefaultPlacement
		*out = new(Placement)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OnCamelKAPIBinding.
func (in *OnCamelKAPIBinding) DeepCopy() *OnCamelKAPIBinding {
	if in == nil {
		return nil
	}
	out := new(OnCamelKAPIBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OnKaotoAPIBinding) DeepCopyInto(out *OnKaotoAPIBinding) {
	*out = *in
	if in.DefaultPlacement != nil {
		in, out := &in.DefaultPlacement, &out.DefaultPlacement
		*out = new(Placement)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OnKaotoAPIBinding.
func (in *OnKaotoAPIBinding) DeepCopy() *OnKaotoAPIBinding {
	if in == nil {
		return nil
	}
	out := new(OnKaotoAPIBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Placement) DeepCopyInto(out *Placement) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Placement.
func (in *Placement) DeepCopy() *Placement {
	if in == nil {
		return nil
	}
	out := new(Placement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConfiguration) DeepCopyInto(out *ServiceConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.ControllerManagerConfigurationSpec.DeepCopyInto(&out.ControllerManagerConfigurationSpec)
	in.Service.DeepCopyInto(&out.Service)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConfiguration.
func (in *ServiceConfiguration) DeepCopy() *ServiceConfiguration {
	if in == nil {
		return nil
	}
	out := new(ServiceConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConfigurationSpec) DeepCopyInto(out *ServiceConfigurationSpec) {
	*out = *in
	in.APIExports.DeepCopyInto(&out.APIExports)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConfigurationSpec.
func (in *ServiceConfigurationSpec) DeepCopy() *ServiceConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}
